apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctdenoiser
  namespace: usd-djha 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-central
  resources:
    requests:
      storage: 100Gi